// clock_control.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module clock_control (
		input  wire  inclk,  //  altclkctrl_input.inclk
		output wire  outclk  // altclkctrl_output.outclk
	);

	clock_control_altclkctrl_181_bylxp4y clock_control (
		.inclk  (inclk),  //   input,  width = 1,  altclkctrl_input.inclk
		.outclk (outclk)  //  output,  width = 1, altclkctrl_output.outclk
	);

endmodule
