// gxb_rx_reset.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module gxb_rx_reset (
		input  wire       clock,              //              clock.clk
		input  wire       reset,              //              reset.reset
		output wire [2:0] rx_analogreset,     //     rx_analogreset.rx_analogreset
		output wire [2:0] rx_digitalreset,    //    rx_digitalreset.rx_digitalreset
		output wire [2:0] rx_ready,           //           rx_ready.rx_ready
		input  wire [2:0] rx_is_lockedtodata, // rx_is_lockedtodata.rx_is_lockedtodata
		input  wire [2:0] rx_cal_busy         //        rx_cal_busy.rx_cal_busy
	);

	altera_xcvr_reset_control #(
		.CHANNELS              (3),
		.PLLS                  (1),
		.SYS_CLK_IN_MHZ        (100),
		.SYNCHRONIZE_RESET     (1),
		.REDUCED_SIM_TIME      (1),
		.TX_PLL_ENABLE         (0),
		.T_PLL_POWERDOWN       (1000),
		.SYNCHRONIZE_PLL_RESET (0),
		.TX_ENABLE             (0),
		.TX_PER_CHANNEL        (0),
		.T_TX_ANALOGRESET      (0),
		.T_TX_DIGITALRESET     (20),
		.T_PLL_LOCK_HYST       (0),
		.EN_PLL_CAL_BUSY       (0),
		.RX_ENABLE             (1),
		.RX_PER_CHANNEL        (1),
		.T_RX_ANALOGRESET      (70000),
		.T_RX_DIGITALRESET     (4000)
	) gxb_rx_reset (
		.clock              (clock),              //   input,  width = 1,              clock.clk
		.reset              (reset),              //   input,  width = 1,              reset.reset
		.rx_analogreset     (rx_analogreset),     //  output,  width = 3,     rx_analogreset.rx_analogreset
		.rx_digitalreset    (rx_digitalreset),    //  output,  width = 3,    rx_digitalreset.rx_digitalreset
		.rx_ready           (rx_ready),           //  output,  width = 3,           rx_ready.rx_ready
		.rx_is_lockedtodata (rx_is_lockedtodata), //   input,  width = 3, rx_is_lockedtodata.rx_is_lockedtodata
		.rx_cal_busy        (rx_cal_busy),        //   input,  width = 3,        rx_cal_busy.rx_cal_busy
		.pll_powerdown      (),                   // (terminated),                                
		.tx_analogreset     (),                   // (terminated),                                
		.tx_digitalreset    (),                   // (terminated),                                
		.tx_ready           (),                   // (terminated),                                
		.pll_locked         (1'b0),               // (terminated),                                
		.pll_select         (1'b0),               // (terminated),                                
		.tx_cal_busy        (3'b000),             // (terminated),                                
		.pll_cal_busy       (1'b0),               // (terminated),                                
		.tx_manual          (3'b111),             // (terminated),                                
		.rx_manual          (3'b000),             // (terminated),                                
		.tx_digitalreset_or (3'b000),             // (terminated),                                
		.rx_digitalreset_or (3'b000)              // (terminated),                                
	);

endmodule
