// edid_ram.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module edid_ram (
		input  wire [7:0] data,    //    data.datain
		output wire [7:0] q,       //       q.dataout
		input  wire [7:0] address, // address.address
		input  wire       wren,    //    wren.wren
		input  wire       clock,   //   clock.clk
		input  wire       rden     //    rden.rden
	);

	edid_ram_ram_1port_181_smqn75y edid_ram (
		.data    (data),    //   input,  width = 8,    data.datain
		.q       (q),       //  output,  width = 8,       q.dataout
		.address (address), //   input,  width = 8, address.address
		.wren    (wren),    //   input,  width = 1,    wren.wren
		.clock   (clock),   //   input,  width = 1,   clock.clk
		.rden    (rden)     //   input,  width = 1,    rden.rden
	);

endmodule
