// fixedDSP.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module fixedDSP (
		input  wire [17:0] ay,      //      ay.ay
		input  wire [17:0] by,      //      by.by
		input  wire [17:0] ax,      //      ax.ax
		input  wire [17:0] bx,      //      bx.bx
		output wire [63:0] resulta  // resulta.resulta
	);

	fixedDSP_altera_c10gx_native_fixed_point_dsp_181_usubljq c10gx_native_fixed_point_dsp_0 (
		.ay      (ay),      //   input,  width = 18,      ay.ay
		.by      (by),      //   input,  width = 18,      by.by
		.ax      (ax),      //   input,  width = 18,      ax.ax
		.bx      (bx),      //   input,  width = 18,      bx.bx
		.resulta (resulta)  //  output,  width = 64, resulta.resulta
	);

endmodule
