// issp2.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module issp2 (
		output wire [0:0]   source, // sources.source
		input  wire [437:0] probe   //  probes.probe
	);

	altsource_probe_top #(
		.sld_auto_instance_index ("YES"),
		.sld_instance_index      (0),
		.instance_id             ("NONE"),
		.probe_width             (438),
		.source_width            (1),
		.source_initial_value    ("0"),
		.enable_metastability    ("NO")
	) in_system_sources_probes_0 (
		.source     (source), //  output,    width = 1, sources.source
		.probe      (probe),  //   input,  width = 438,  probes.probe
		.source_ena (1'b1)    // (terminated),                       
	);

endmodule
