// para_add.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module para_add (
		input  wire [18:0] data0x, //  parallel_add_input.data0x
		input  wire [18:0] data1x, //                    .data1x
		input  wire [18:0] data2x, //                    .data2x
		output wire [20:0] result  // parallel_add_output.result
	);

	para_add_parallel_add_181_pflxnwy parallel_add_0 (
		.data0x (data0x), //   input,  width = 19,  parallel_add_input.data0x
		.data1x (data1x), //   input,  width = 19,                    .data1x
		.data2x (data2x), //   input,  width = 19,                    .data2x
		.result (result)  //  output,  width = 21, parallel_add_output.result
	);

endmodule
