// pll_hdmi.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module pll_hdmi (
		input  wire        rst,               //             reset.reset
		input  wire        refclk,            //            refclk.clk
		output wire        locked,            //            locked.export
		input  wire [63:0] reconfig_to_pll,   //   reconfig_to_pll.reconfig_to_pll
		output wire [63:0] reconfig_from_pll, // reconfig_from_pll.reconfig_from_pll
		output wire        outclk_0,          //           outclk0.clk
		output wire        outclk_1,          //           outclk1.clk
		output wire        outclk_2           //           outclk2.clk
	);

	pll_hdmi_altera_iopll_181_apwsf4a pll_hdmi (
		.rst               (rst),               //   input,   width = 1,             reset.reset
		.refclk            (refclk),            //   input,   width = 1,            refclk.clk
		.locked            (locked),            //  output,   width = 1,            locked.export
		.reconfig_to_pll   (reconfig_to_pll),   //   input,  width = 64,   reconfig_to_pll.reconfig_to_pll
		.reconfig_from_pll (reconfig_from_pll), //  output,  width = 64, reconfig_from_pll.reconfig_from_pll
		.outclk_0          (outclk_0),          //  output,   width = 1,           outclk0.clk
		.outclk_1          (outclk_1),          //  output,   width = 1,           outclk1.clk
		.outclk_2          (outclk_2)           //  output,   width = 1,           outclk2.clk
	);

endmodule
